name: Deploy to Pi (GitOps)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r llamatrama_agent/requirements.txt
      # Add your deployment step here (e.g., rsync, scp, or SSH to Pi)
      - name: Deploy to Pi (example)
        env:
          PI_HOST: ${{ secrets.PI_HOST }}
          PI_USER: ${{ secrets.PI_USER }}
          PI_KEY: ${{ secrets.PI_KEY }}
        run: |
          echo "$PI_KEY" > key.pem
          chmod 600 key.pem
          rsync -avz --exclude 'venv' --exclude '.git' -e "ssh -i key.pem -o StrictHostKeyChecking=no" . $PI_USER@$PI_HOST:~/executa-llama/
          ssh -i key.pem -o StrictHostKeyChecking=no $PI_USER@$PI_HOST 'cd ~/executa-llama && .venv/bin/pip install -r llamatrama_agent/requirements.txt && sudo systemctl restart executa-llama || true'
